In normal list while adding list, its concat

In [ ]:
#
a = [1,2,3,4]
b = [1,2,3,4]
c = a + b
print(c)

[1, 2, 3, 4, 1, 2, 3, 4]


Lets add list using numpy
1D ARRAY


In [8]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(type(a))
print(type(b))


print(a+b)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[2 4 6 8]


2D ARRAY


In [ ]:
two_d_array = np.array([
   [1,2,3],
   [1,2,3],
   [1,2,3]
)

print(two_d_array)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
