In normal list while adding list, its concat

In [ ]:
#
a = [1,2,3,4]
b = [1,2,3,4]
c = a + b
print(c)

[1, 2, 3, 4, 1, 2, 3, 4]


Lets add list using numpy
1D ARRAY

NumPy -> Used for Numerical Calculation



In [8]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(type(a))
print(type(b))


print(a+b)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[2 4 6 8]


2D ARRAY


In [12]:
two_d_array = np.array([
   [1,2,3],
   [1,2,3],
   [1,2,3]
])

print(two_d_array)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#For 1D ARRAY

#zeros, ones, arrange
#Rows and Columns

zero_array = np.zeros(5)
print(zero_array)

#zeros fucntion always gives i n float , we can change datatype if we want in integer
zero_arr = np.zeros(5, dtype = int)
print(zero_arr)

#same goes for ones
one_array = np.ones(5)
print(one_array)

one_arr = np.ones(5, dtype = int)
print(one_arr)

#arrange 
#start:stop:step

range_data = np.arange(0,10,2)
print(range_data)



: 

In [72]:
#For 2D ARRAY

zero_2D_array = np.zeros((5,2))
print(zero_2D_array)

#zeros fucntion always gives in float , we can change datatype if we want in integer
zero_2D_arr = np.zeros((5,20), dtype = int)
print(zero_2D_arr)

#same goes for ones
one_2D_array = np.ones((5,2))
print(one_2D_array)

one_2D_arr = np.ones((5,2), dtype = int)
print(one_2D_arr)





[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


TO CONVERT MULTI-DIM array into 1D ARRAY

We have 2 function:

    a. Ravel -> convert multi dim into 1D

    b. Reshape ->  convert 1D into multi dim

In [33]:
print(zero_2D_array)

print("")
print("This above array is 2D array")
print("ravel convert it into 1D")
print("")
Ravel_array = np.ravel(zero_2D_array)
print(Ravel_array)


print("")
print("Reshape is used to convert 1D into 2D")



[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

This above array is 2D array
ravel convert it into 1D

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Reshape is used to convert 1D into 2D


INDEXING AND SLICING

In [ ]:
'''
Positive Index : Starts from 0
Negative Index : Starts from -1

Concept useful for Conditional Filtering 
   Conditional Filtering is based on Bolean Indexing
'''

In [ ]:
#For 1D ARRAY
#start:stop:step
num = np.array([1,2,3,4,5,6,7,8,9,10])
print(num[1:10:2])
print(num[:10:2])
print(num[1::2])
print(num[::2])




[ 2  4  6  8 10]
[1 3 5 7 9]
[ 2  4  6  8 10]
[1 3 5 7 9]


In [54]:
#2D Slicing -> used for feature extraction and sample data extraction

zero_2D_arrayy = np.zeros((5,4))
print(zero_2D_arrayy)

#multi_d_arr[row , col]
print("")
print(zero_2D_arrayy[0:2, 0:2])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0.]
 [0. 0.]]


In [ ]:
#BOLEAN INDEXING
'''
 Can be used to filter numerical value, string value
 ---------------------------------------------------
'''
salary = np.array([10000,12000,14000,9000,15000])
print("Lets filter salary for >12000")
print("salary : ",salary)
filtered_salary = salary > 12000
print(filtered_salary)

print("")
print("Now if we want actual values instead of bolean values")
print(salary[filtered_salary])
print("")


emp_name = np.array(['Ram','Shyam',"Hari","Rita"])
print("Name : ",emp_name)




Lets filter salary for >12000
salary :  [10000 12000 14000  9000 15000]
[False False  True False  True]

Now if we want actual values instead of bolean values
[14000 15000]

Name :  ['Ram' 'Shyam' 'Hari' 'Rita']


In [ ]:
#ARRAY BROADCASTING

'''
Array BROADCASTING -> Broadcasting in NumPy allows us to perform 
                     arithmetic operations on arrays of different shapes without reshaping them. 
---------

For 1D:

Rule 1 -> Size equal
Rule 2 -> Any one array shape should be 1 
'''
num_one = np.array([
    [1,2,3]
])

num_two = np.array([1])
print(num_one + num_two)

'''
For 2D:
 Rule 1 -> Size of array should be equal
 Rule 2 -> Either row or column should be equal , only when if row are equal then column should have 1
                                                            else column are equal then row should have 1 in any one of array
                                                        
'''

[[2 3 4]]


'\nFor 2D:\n Rule 1 -> Size of array should be equal\n Rule 2 -> Either row or column should be equal , only when if row are equal then column should have 1\n                                                            else column are equal then row should have 1 in any one of array\n'